#!/bin/bash
# Adapted from raspberrypi-motd by ar5ian (https://github.com/ar51an/raspberrypi-motd) 
# by justinlevinedotme (https://github.com/justinlevinedotme)

function color (){
  local fg=$1
  local bg=$2
  local bold=$3
  local text=$4

  local fgCode=$(tput setaf $fg)
  local bgCode=$(tput setab $bg)
  local resetCode=$(tput sgr0)
  local boldCode=""

  if [ "$bold" == "true" ]; then
    boldCode=$(tput bold)
  fi

  echo "${boldCode}${fgCode}${bgCode}${text}${resetCode}"
}

function sec2time (){
  local input=$1

  ((days=input/86400))
  ((input=input%86400))
  ((hours=input/3600))
  ((input=input%3600))
  ((mins=input/60))

  local daysPlural="s"
  local hoursPlural="s"
  local minsPlural="s"

  if [[ $days -eq 0 ||  $days -eq 1 ]]; then
    daysPlural=""
  fi
  if [[ $hours -eq 0 || $hours -eq 1 ]]; then
    hoursPlural=""
  fi
  if [[ $mins -eq 0 || $mins -eq 1 ]]; then
    minsPlural=""
  fi
  echo "$days day$daysPlural $hours hr$hoursPlural $mins min$minsPlural"
}

#Color Configs
#statsLabelColor = the actual stats of your machine.
statsLabelColorFg=7  # White
statsLabelColorBg=0  # Default background
statsLabelBold=false

#bulletColor = the final "." before showing the stats
bulletColorFg=8  # Dark gray
bulletColorBg=0  # Default background
bulletBold=false

#infoColor = labels like "LAST, or IP"
infoColorFg=87  # #60FDFF
infoColorBg=0  # Default background
infoBold=true

#dimInfoColor = sub labels like * 05-20-24 11:50
dimInfoColorFg=8  # Dim version of #60FDFF
dimInfoColorBg=0  # Default background
dimInfoBold=false

resetColor=$(tput sgr0)
me=$(logname)

# Last Login
read loginIP loginDate <<< $(last $me --time-format iso -2 | awk 'NR==1 { print $3,$4 }')
if [[ $loginDate == *T* ]]; then
  login="$(date -d $loginDate +"%a %b %d %Y, %I:%M %p") $(color $dimInfoColorFg $dimInfoColorBg $dimInfoBold)"
else
  # First Login
  login="None"
fi

# Stats
label1="$login"
label1="$(color $infoColorFg $infoColorBg $infoBold "Last") $(color $bulletColorFg $bulletColorBg $bulletBold "....") $(color $infoColorFg $infoColorBg $infoBold ".") $(color $statsLabelColorFg $statsLabelColorBg $statsLabelBold "$label1")"

label2="$(vcgencmd measure_temp | cut -c "6-9")°C"
label2="$(color $infoColorFg $infoColorBg $infoBold "Temp") $(color $bulletColorFg $bulletColorBg $bulletBold "...") $(color $infoColorFg $infoColorBg $infoBold ".") $(color $statsLabelColorFg $statsLabelColorBg $statsLabelBold "$label2")"

uptime="$(sec2time $(cut -d "." -f 1 /proc/uptime))"
uptime="$uptime $(color $dimInfoColorFg $dimInfoColorBg $dimInfoBold "* $(date -d @$(grep btime /proc/stat | cut -d " " -f 2) +"%m-%d-%y %H:%M")")"

label3="$uptime"
label3="$(color $infoColorFg $infoColorBg $infoBold "Uptime") $(color $bulletColorFg $bulletColorBg $bulletBold "..") $(color $infoColorFg $infoColorBg $infoBold ".") $(color $statsLabelColorFg $statsLabelColorBg $statsLabelBold "$label3")"

label4="$(awk -v a="$(awk '/cpu /{print $2+$3+$4+$5+$6+$7+$8+$9+$10,$5}' /proc/stat; sleep 0.3)" '/cpu /{split(a,b," "); printf "%.1f%%", 100*(($2+$3+$4+$5+$6+$7+$8+$9+$10-b[1])-($5-b[2]))/($2+$3+$4+$5+$6+$7+$8+$9+$10-b[1])}' /proc/stat)"
label4="$(color $infoColorFg $infoColorBg $infoBold "Cpu") $(color $bulletColorFg $bulletColorBg $bulletBold "....") $(color $infoColorFg $infoColorBg $infoBold ".") $(color $statsLabelColorFg $statsLabelColorBg $statsLabelBold "$label4")"

label5="$(df -h ~ | awk 'NR==2 { printf "%sB / %sB * Free: %sB",$3,$2,$4; }')"
label5="$(color $infoColorFg $infoColorBg $infoBold "Disk") $(color $bulletColorFg $bulletColorBg $bulletBold "....") $(color $infoColorFg $infoColorBg $infoBold ".") $(color $statsLabelColorFg $statsLabelColorBg $statsLabelBold "$label5")"

label6="$(/bin/ls -d /proc/[0-9]* | wc -l)"
label6="$(color $infoColorFg $infoColorBg $infoBold "Procs") $(color $bulletColorFg $bulletColorBg $bulletBold "..") $(color $infoColorFg $infoColorBg $infoBold ".") $(color $statsLabelColorFg $statsLabelColorBg $statsLabelBold "$label6")"

label7="$(free -h --si | awk 'NR==2 { printf "%sB / %sB * Free: %sB",$3,$2,$4; }')"
label7="$(color $infoColorFg $infoColorBg $infoBold "Memory") $(color $bulletColorFg $bulletColorBg $bulletBold "..") $(color $infoColorFg $infoColorBg $infoBold ".") $(color $statsLabelColorFg $statsLabelColorBg $statsLabelBold "$label7")"

label8="$(curl ipv4.icanhazip.com -s)"
label8="$(color $infoColorFg $infoColorBg $infoBold "IP") $(color $bulletColorFg $bulletColorBg $bulletBold ".....") $(color $infoColorFg $infoColorBg $infoBold ".") $(color $statsLabelColorFg $statsLabelColorBg $statsLabelBold "$label8")"

# Print
echo
# Two Entries Per Line
echo -e "                                                         $label2\r   $label1"
echo -e "                                                         $label4\r   $label3"
echo -e "                                                         $label6\r   $label5"
echo -e "                                                         $label8\r   $label7"
